export const PARTICLE_GLOSSES = {
  "δέ": "but, and",
  "δε": "but, and",
  "γάρ": "for, because",
  "γαρ": "for, because",
  "μέν": "on the one hand; indeed",
  "μεν": "on the one hand; indeed",
  "καί": "and, also, even",
  "και": "and, also, even",
  "τε": "and",
  "ἤ": "or, than",
  "η": "or, than",
  "οὐ": "not",
  "ου": "not",
  "οὐκ": "not",
  "οὐχ": "not",
  "μή": "not; lest",
  "μη": "not; lest",
  "ἄν": "modal particle",
  "αν": "modal particle",
  "γε": "at least, indeed",
  "ἆρα": "then? surely?",
  "αρα": "then? surely?",  
  "Χρύσην": "Chryses",
  "χρυσην": "Chryses",
  "ἠτίμασεν": "dishonored, slighted",
  "ητιμασεν": "dishonored, slighted",

};